services:
  nginx:
    container_name: nginx
    build:
      context: ./containers
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ft_frontend:/home
volumes:
  ft_frontend:
    driver: local
    driver_opts:
      type: none
      device: /mnt/c/Users/mel-mars/Desktop/ft_frontend
      o: bind
